site_name: socialgene
site_url: https://chasemc.github.io
nav:
        - Home: home.md
        - "System Requirements": "system.md"
        - "Advanced Start": "advanced_start.md"
        - "Ultra-Quickstart!": "ultraquickstart.md"
        - "Nextflow":
                  - "Install Nextflow": "nextflow/install_nextflow.md"
                  - "Quickstart": "nextflow/quickstart.md"
                  - "Genome Inputs": "nextflow/genome_inputs.md"
                  - "Build DB from taxon name": "nextflow/build_taxa.md"
                  - "Outputs": "nextflow/outputs.md"
                  - "Docker and the Nextflow Pipeline": "nextflow/nextflow_docker_images.md"
        - "Python":
                  - "Installation": "python/installation.md"
                  - "Main Classes": "python/socialgene_classes.md"
                  - "API": "python_api.md"
        - "Django":
                  - "Setup": "django/django.md"
                  - "Quick start": "django/quickstart.md"
                  - "Advanced": "django/advanced.md"
                  - "Contributing": "django/contributing.md"
        - "Developing":
                  - "Python":
                            - "Setup": "developing/python/setup.md"
                            - "Testing": "developing/python/testing.md"

plugins:
        - search
        - autorefs
        - mkdocstrings
#        - mkdocs-coverage:
#                  page_name: coverage # default
#                  html_report_dir: htmlcov # default

theme:
        name: material

extra_css:
        - stylesheets/extra.css
