site_name: socialgene
site_url: https://chasemc.github.io
nav:
        - Home: home.md
        - "System Requirements": "system_requirements.md"
        - "Ultra-Quickstart!": "ultraquickstart.md"
        - "Building a Database (Nextflow)":
                  - "Installation": "nextflow/install_nextflow.md"
                  - "Genome Inputs": "nextflow/genome_inputs.md"
                  - "Outputs": "nextflow/outputs.md"
                  - "Overview": "nextflow/quickstart.md"
                  - "Running the Piepeline": "advanced_start.md"
                  - "Docker Images": "nextflow/nextflow_docker_images.md"
                  - "Examples": "nextflow/examples.md"
        - "Web Interface (Django)":
                  - "Setup": "django/django.md"
                  - "Quick start": "django/quickstart.md"
                  - "Advanced": "django/advanced.md"
                  - "Contributing": "django/contributing.md"
        - "Developing":
                  - "Python":
                            - "Setup": "developing/python/setup.md"
                            - "Testing": "developing/python/testing.md"

plugins:
        - search
        - autorefs
        - mkdocstrings
#        - mkdocs-coverage:
#                  page_name: coverage # default
#                  html_report_dir: htmlcov # default

theme:
        name: material

extra_css:
        - stylesheets/extra.css
