site_name: "SocialGene"
site_url: https://chasemc.github.io
repo_url: https://github.com/socialgene/socialgene.github.io
edit_uri: edit/main/docs/
nav:
        - "index.md"
        - "System Requirements": "system_requirements.md"
        - "Ultra-Quickstart!": "ultraquickstart/ultraquickstart.md"
        - "Building a Database (Nextflow)":
                  - "Installation": "nextflow/installation.md"
                  - "Inputs": "nextflow/inputs.md"
                  - "Parameters": "nextflow/parameters.md"
                  - "Outputs": "nextflow/outputs.md"
                  - "Running the Workflow": "nextflow/running_the_pipeline.md"
                  - "Examples": "nextflow/examples.md"
                  - "Advanced":
                            - "Docker Images": "nextflow/docker_images.md"
        - "Nodes and Relationships":
                  - "Identifiers": "nodes_and_relationships/about_the_database.md"
                  - "Schema": "nodes_and_relationships/schema.md"
        - "Interacting with a Database (Neo4j)":
                  - "Database Launch": "neo4j/database_launch.md"
                  - "Database Backups": "neo4j/database_backups.md"
                  - "Interacting": "neo4j/interacting.md"
                  - "Running the Database with Slurm": "neo4j/slurm.md"
        # - "Web Interface (Django)":
        #           - "Setup": "django/django.md"
        #           - "Quick start": "django/quickstart.md"
        #           - "Advanced": "django/advanced.md"
        #           - "Contributing": "django/contributing.md"
        - "Developing":
                  - "Python":
                            - "Setup": "developing/python/setup.md"
                            - "Classes": "developing/python/classes.md"
                            - "Testing": "developing/python/testing.md"
                            - Auto-Generated Reference: reference/ #
        - "Presentations": "presentations/presentations.md"

        - "Give Feedback": "feedback.md"

plugins:
        - search
        - autorefs
        - gen-files:
                  scripts:
                          - docs/gen_ref_pages.py
        - literate-nav:
                  nav_file: developing/python/reference/SUMMARY.md
        - section-index
        - mkdocstrings
markdown_extensions:
        - attr_list
        - admonition
        - pymdownx.details
        - pymdownx.superfences
        - pymdownx.tabbed:
                  alternate_style: true

theme:
        name: material
        features:
                - content.action.edit
                - content.code.copy
        favicon: media/single.png

extra_css:
        - stylesheets/extra.css

extra:
        analytics:
                provider: google
                property: G-6NNX9NGJ09
                feedback:
                        title: Was this page helpful?
                        ratings:
                                - icon: material/emoticon-happy-outline
                                  name: This page was helpful
                                  data: 1
                                  note: >-
                                          Thanks for your feedback!
                                - icon: material/emoticon-sad-outline
                                  name: This page could be improved
                                  data: 0
                                  note: >-
                                          Thanks for your feedback! Help us improve this page by
                                          using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
