site_name: socialgene
site_url: https://chasemc.github.io
nav:
        - Home: home.md
        - "Overview": "overview.md"
        - "Ultra-Quickstart!": "ultraquickstart.md"
        - "Nextflow":
                  - "Install Nextflow": "nextflow/install_nextflow.md"
                  - "Quickstart": "nextflow/quickstart.md"
                  - "Genome Inputs": "nextflow/genome_inputs.md"
                  - "Build DB from taxon name": "nextflow/build_taxa.md"
                  - "Outputs": "nextflow/outputs.md"
        - "Python":
                  - "Installation": "python/installation.md"
                  - "Main Classes": "python/socialgene_classes.md"
                  - "API": "python_api.md"
        - "Django":
                  - "Setup": "django/django.md"
                  - "Quick start": "django/quickstart.md"
                  - "Advanced": "django/advanced.md"
                  - "Contributing": "django/contributing.md"
        - "Developing":
                  - "Testing":
                            - "Python": "developing/testingpython.md"
                  - "Python":
                            - "Classes": "developing/python/classes.md"
                  - "Docker":
                            - "Docker and the Nextflow Pipeline": "developing/docker/nextflow_docker_images.md"
plugins:
        - search
        - autorefs
        - mkdocstrings
#        - mkdocs-coverage:
#                  page_name: coverage # default
#                  html_report_dir: htmlcov # default

theme:
        name: material

extra_css:
        - stylesheets/extra.css
