site_name: "SocialGene"
site_url: https://chasemc.github.io
repo_url: https://github.com/socialgene
edit_uri: edit/main/docs/
nav:
        - "index.md"
        - "System Requirements": "system_requirements.md"
        - "Ultra-Quickstart!": "ultraquickstart/ultraquickstart.md"
        - "Building a Database (Nextflow)":
                  - "Installation": "nextflow/installation.md"
                  - "Inputs": "nextflow/inputs.md"
                  - "Parameters": "nextflow/parameters.md"
                  - "Outputs": "nextflow/outputs.md"
                  - "Running the Workflow": "nextflow/running_the_pipeline.md"
                  - "Examples": "nextflow/examples.md"
                  - "Advanced":
                            - "Docker Images": "nextflow/docker_images.md"
        - "Nodes and Relationships":
                  - "Identifiers": "nodes_and_relationships/about_the_database.md"
                  - "Nodes": "nodes_and_relationships/nodes.md"
                  - "Relationships": "nodes_and_relationships/relationships.md"
        - "Interacting with a Database (Neo4j)":
                  - "Database Launch": "neo4j/database_launch.md"
                  - "Database Backups": "neo4j/database_backups.md"
                  - "Interacting": "neo4j/interacting.md"
                  - "Run DB in Slurm": "neo4j/slurm.md"

        # - "Web Interface (Django)":
        #           - "Setup": "django/django.md"
        #           - "Quick start": "django/quickstart.md"
        #           - "Advanced": "django/advanced.md"
        #           - "Contributing": "django/contributing.md"
        - "Developing":
                  - "Python":
                            - "Setup": "developing/python/setup.md"
                            - "Classes": "developing/python/classes.md"
                            - "Testing": "developing/python/testing.md"
                            - Auto-Generated Reference: reference/ #

        - "Give Feedback": "feedback.md"

plugins:
        - search
        - autorefs
        - gen-files:
                  scripts:
                          - docs/gen_ref_pages.py
        - literate-nav:
                  nav_file: developing/python/reference/SUMMARY.md
        - section-index
        - mkdocstrings
markdown_extensions:
        - attr_list
        - admonition
        - pymdownx.details
        - pymdownx.superfences
        - pymdownx.tabbed:
                  alternate_style: true

theme:
        name: material
        features:
                - content.action.edit
                - content.code.copy
        favicon: media/single.png

extra_css:
        - stylesheets/extra.css
